openapi: 3.0.3
info:
  title: French Business Directory API
  description: API pour consulter les entreprises et établissements du répertoire SIRENE.
  version: 1.0.0
servers:
  - url: /api
    description: Serveur API local

paths:
  /tokens/create:
    post:
      summary: Créer un jeton d'accès
      operationId: createToken
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - token_name
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: secret123
                token_name:
                  type: string
                  example: my-token
      responses:
        '201':
          description: Jeton créé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: 1|abcdef123456
        '401':
          description: Identifiants invalides
        '422':
          description: Erreur de validation

  /etablissements/siren/{siren}:
    get:
      summary: Liste des établissements par SIREN
      operationId: getEtablissementsBySiren
      tags:
        - Etablissements
      security:
        - bearerAuth: []
      parameters:
        - name: siren
          in: path
          required: true
          description: Le numéro SIREN (9 chiffres)
          schema:
            type: string
            pattern: '^[0-9]{9}$'
      responses:
        '200':
          description: Liste des établissements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Etablissement'
        '400':
          description: En-tête SIREN requis (ou erreur de paramètre)
        '401':
          description: Non authentifié

  /etablissements/siret/{siret}:
    get:
      summary: Récupérer un établissement par SIRET
      operationId: getEtablissementBySiret
      tags:
        - Etablissements
      security:
        - bearerAuth: []
      parameters:
        - name: siret
          in: path
          required: true
          description: Le numéro SIRET (14 chiffres)
          schema:
            type: string
            pattern: '^[0-9]{14}$'
      responses:
        '200':
          description: Détails de l'établissement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Etablissement'
        '400':
          description: SIRET requis
        '401':
          description: Non authentifié

  /entreprises/siren/{siren}:
    get:
      summary: Récupérer une entreprise par SIREN
      operationId: getEntrepriseBySiren
      tags:
        - Entreprises
      security:
        - bearerAuth: []
      parameters:
        - name: siren
          in: path
          required: true
          description: Le numéro SIREN (9 chiffres)
          schema:
            type: string
            pattern: '^[0-9]{9}$'
      responses:
        '200':
          description: Détails de l'entreprise
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entreprise'
        '400':
          description: SIREN requis
        '401':
          description: Non authentifié

  /entreprises/name/{name}:
    get:
      summary: Rechercher des entreprises par nom
      operationId: searchEntreprisesByName
      tags:
        - Entreprises
      security:
        - bearerAuth: []
      parameters:
        - name: name
          in: path
          required: true
          description: Nom ou dénomination de l'entreprise
          schema:
            type: string
            minLength: 2
            maxLength: 100
      responses:
        '200':
          description: Liste des entreprises correspondantes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entreprise'
        '401':
          description: Non authentifié

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Entreprise:
      type: object
      properties:
        siren:
          type: integer
          example: 123456789
        statutDiffusionUniteLegale:
          type: string
        unitePurgeeUniteLegale:
          type: string
          nullable: true
        dateCreationUniteLegale:
          type: string
          format: date
          nullable: true
        sigleUniteLegale:
          type: string
          nullable: true
        sexeUniteLegale:
          type: string
          nullable: true
        prenom1UniteLegale:
          type: string
          nullable: true
        prenom2UniteLegale:
          type: string
          nullable: true
        prenom3UniteLegale:
          type: string
          nullable: true
        prenom4UniteLegale:
          type: string
          nullable: true
        prenomUsuelUniteLegale:
          type: string
          nullable: true
        pseudonymeUniteLegale:
          type: string
          nullable: true
        identifiantAssociationUniteLegale:
          type: string
          nullable: true
        trancheEffectifsUniteLegale:
          type: string
        anneeEffectifsUniteLegale:
          type: number
          nullable: true
        dateDernierTraitementUniteLegale:
          type: string
          format: date-time
        nombrePeriodesUniteLegale:
          type: integer
        categorieEntreprise:
          type: string
          nullable: true
        anneeCategorieEntreprise:
          type: number
          nullable: true
        dateDebut:
          type: string
          format: date
          nullable: true
        etatAdministratifUniteLegale:
          type: string
        nomUniteLegale:
          type: string
          nullable: true
        nomUsageUniteLegale:
          type: string
          nullable: true
        denominationUniteLegale:
          type: string
          nullable: true
        denominationUsuelle1UniteLegale:
          type: string
          nullable: true
        denominationUsuelle2UniteLegale:
          type: string
          nullable: true
        denominationUsuelle3UniteLegale:
          type: string
          nullable: true
        categorieJuridiqueUniteLegale:
          type: integer
        activitePrincipaleUniteLegale:
          type: string
          nullable: true
        nomenclatureActivitePrincipaleUniteLegale:
          type: string
          nullable: true
        nicSiegeUniteLegale:
          type: integer
        economieSocialeSolidaireUniteLegale:
          type: string
          nullable: true
        societeMissionUniteLegale:
          type: string
          nullable: true
        caractereEmployeurUniteLegale:
          type: number
          nullable: true
        activitePrincipaleNAF25UniteLegale:
          type: string
          nullable: true

    Etablissement:
      type: object
      properties:
        siren:
          type: integer
        nic:
          type: integer
        siret:
          type: integer
        dateFin:
          type: string
          format: date
          nullable: true
        dateDebut:
          type: string
          format: date
          nullable: true
        etatAdministratifEtablissement:
          type: string
          nullable: true
        changementEtatAdministratifEtablissement:
          type: boolean
        enseigne1Etablissement:
          type: string
          nullable: true
        enseigne2Etablissement:
          type: string
          nullable: true
        enseigne3Etablissement:
          type: string
          nullable: true
        changementEnseigneEtablissement:
          type: boolean
        denominationUsuelleEtablissement:
          type: string
          nullable: true
        changementDenominationUsuelleEtablissement:
          type: boolean
        activitePrincipaleEtablissement:
          type: string
          nullable: true
        nomenclatureActivitePrincipaleEtablissement:
          type: string
          nullable: true
        changementActivitePrincipaleEtablissement:
          type: boolean
        caractereEmployeurEtablissement:
          type: string
          nullable: true
        changementCaractereEmployeurEtablissement:
          type: boolean
